language: csharp
mono: none
dotnet: 2.1.402
before_script:
- dotnet restore
script:
- dotnet test ./XUnitTests1 -c Release -f netcoreapp2.1
deploy:
  provider: heroku
  api_key:
    secure: ngd2mBv2ltaeekRpmNUdilYRUkRpBrJzIjjMe7uRgm8ZHKPwnPG6EsJK10K7F6m3lUnRMe/AadJx9NU8rOsihdSEdVhItgxtRMvbUsxLkna6/cSe3O3gpOznWo3erinj8EuYJoqECS+dBrW2kQFA0u/quiv8Hb7O7rYBxGtGP74DjDYFoL9rDo3JWfHUDzCmNnqkFx104GqlheFO2cYc7yiTemRQIQ4vqZcLxpA0DwKhBKM1r6gubJbhA77W71KfeFacWdXC8rMxkCdbLJvFtGaiklHolycLR+0JtCFXsNfcvHSWfLiOOVtBp/qTKDJBmC6BfwNBe69RsOr1VPsXefPdI8wLq8lZgmkpWRCbT7Ja0GEbP6F0uV83FQJ4airD26UCh1tzfY3AK5cDXj3HDJ4j8vCdjtbidqcR+aasIw/iEGhPGkdMDfg2en3EFFhISO/rLFiNbDRB8J8p8Rm4PJAw30e8kxWTyFXc0wdAd+J3npqESRTOSwTNrbTjMQ2N3J9OArjmo4Zizkq1eiYSciEl/cum/mwYsI7qWy6a+LkReh3TluaeiFBkVSVetHLA9wwPlkI3Lgmu1cb00dyS3HlBi1qWwvgR0iidHWXKqrcLmzsDx/lOriGFddOdk3+/ogRcfg+LnsXYuLA4FsXoY0e2Ci7UTUkbxA7QUFG/2co=
  app: Lab1
